### ISSUE TITLE
Roadmap v0.2.0

### ISSUE THREAD

**Issue by tiepvupsu** [tiepvupsu/tabml#88]
- [ ] support Grid Search
- [x] support XGBoost, CatBoost
- [ ] support deep learning models (TabNet, Pytorch Lighting, etc)
- [x] support deployment
- [x] consider integrate with MLflow
- [ ] auto select trainer from model wrapper, allow users to specify custom trainers
- [ ] integrate with [SHAP](https://github.com/slundberg/shap)
